name: Docker Image Build Test

on:
  pull_request:
    branches: [master, develop]

  # manually run a workflow
  workflow_dispatch:

  # allow this workflow to be called from other workflows
  workflow_call:

env:
  IMAGE_NAME: core-php-fpm-web-server

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/

  test_build:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Run build tests
      run: |
        if [ -f docker-compose.test.yml ]; then
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run sut
        else
          docker build . --no-cache --build-arg APP_ENVIROMENT=production --file Dockerfile
        fi
